version: '3.8'

services:


  db:
    image: "postgres"
    ports:
      - 5436:5432
    hostname: lo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=marat
      - POSTGRES_PASSWORD=ab123
      - POSTGRES_DB=test_db

    container_name: postgres




volumes:
  postgres-data: